controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
